apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnhost
  namespace: default
  labels:
    app: agnhost
spec:
  selector:
    matchLabels:
      app: agnhost
  replicas: 1
  template:
    metadata:
      labels:
        app: agnhost
    spec:
      containers:
        - name: http
          command:
            - /agnhost
            - netexec
            - --http-port
            - "8080"
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: agnhost
spec:
  selector:
    app: agnhost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: other-agnhost
spec:
  selector:
    app: agnhost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
